# This is a basic workflow to help you get started with Actions

name: Validate Template

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install PSScriptAnalyzer
      - name: Install PSScriptAnalyzer and Pester from PSGallery
        shell: pwsh
        run : |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Force
          Install-Module Pester -Force

      # Run PSScriptAnalyzer
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run : |
          Invoke-ScriptAnalyzer -Path *.ps1 -Recurse -OutVariable Issues
          $Errors = $Issues.Where( { $_.Severity -eq 'Error' })
          $Warnings = $Issues.Where( { $_.Severity -eq 'Warning' })
          $Informational = $Issues.Where( { $_.Severity -eq 'Information' })
          if ($errors) { Throw "Errors: $($Errors.Count) `nWarnings: $($Warnings.Count) `nInformational: $($Informational.Count)" }
          else { Write-Output "Errors: $($Errors.Count) `nWarnings: $($Warnings.Count) `nInformational: $($Informational.Count)" }

      # Run Pester
      - name: Run Pester
        shell: pwsh
        run : |
          Invoke-Pester